on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Dist
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - run: |
          npm install angular
          npm install @angular/cli
          npm run build --prod
          ls

  UpdateToAWS:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials@v1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          aws s3 sync dist/. 's3://tttangular'

  createInvalidation:
    runs-on: ubuntu-latest
    needs: UpdateToAWS
    steps:
      - uses: actions/checkout@v3
      - name: Create CloudFront invalidation
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          cd dist
          aws cloudfront create-invalidation --distribution-id ${{ secrets.ID_AWS_CLOUDFRONT }} --paths '/*'
